global:
  scrape_interval: 10s

scrape_configs:
- job_name: victoriametrics
  static_configs:
  - targets:
    - victoriametrics:8428
- job_name: vmalert
  static_configs:
  - targets:
    - vmalert:8880
- job_name: victorialogs
  static_configs:
  - targets:
    - victorialogs:9428

  # This is the block for all prebid cache related scrapes  
  # PBC - Haproxy - metrics
  - job_name: 'PBC - Haproxy'
    scrape_interval: 30s
    static_configs:
      - targets: ['mc-liitpqy4i9.bunny.run:80']
        labels:
          target_name: 'PBC - Haproxy'
          environment: 'production'
          region: 'us-west'
          service: 'metrics'
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: 'instance'
        replacement: 'PBC - Haproxy'  # Replacing instance with a more meaningful name


    # prebid cache related 
  # PBC - Main - metrics
  - job_name: 'PBC - Main'
    scrape_interval: 30s
    static_configs:
      - targets: ['mc-2z711paurd.bunny.run:443']
        labels:
          target_name: 'PBC - Main'
          environment: 'production'
          region: 'us-west'
          service: 'metrics'
    metrics_path: '/metrics'
    scheme: 'https'
    relabel_configs:
      - source_labels: [__address__]
        target_label: 'instance'
        replacement: 'PBC - Main'  # Replacing instance with a more meaningful name

  # PBC - Main - metrics
  - job_name: 'PBC - Central'
    scrape_interval: 30s
    static_configs:
      - targets: ['mc-ryj25x4qb7.bunny.run/:443']
        labels:
          target_name: 'PBC - Central'
          environment: 'production'
          region: 'us-west'
          service: 'metrics'
    metrics_path: '/metrics'
    scheme: 'https'
    relabel_configs:
      - source_labels: [__address__]
        target_label: 'instance'
        replacement: 'PBC - Central'  # Replacing instance with a more meaningful name

  



  # This is the block for all prebid server related scrapes
  # PBS - Main - metrics
  - job_name: 'PBS - Main'
    scrape_interval: 30s
    static_configs:
      - targets: ['mc-znvva6c0j7.bunny.run:443']
        labels:
          target_name: 'PBS - Main'
          environment: 'production'
          region: 'us-west'
          service: 'metrics'
    metrics_path: '/metrics'
    scheme: 'https'
    relabel_configs:
      - source_labels: [__address__]
        target_label: 'instance'
        replacement: 'PBS - Main'  # Replacing instance with a more meaningful name





  # Valkey - Central - metrics
  # PBS - Vitess - metrics